# Generated by Django 5.0.7 on 2024-08-06 01:19

import job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default=1, upload_to=job.models.img_upload),
            preserve_default=False,
        ),
    ]
